### ISSUE TITLE
Add a output to d3_js with networkx (feature request)

### ISSUE THREAD

**Issue by alvations** [goodmami/pydelphin#22]
It would be nice if you would add a dump function to dump the networkx graph into a d3 javascript, then we can view it beautifully on the web browser. http://drewconway.com/zia/2013/3/26/visualizing-networkx-graphs-in-the-browser-using-d3

**Comment by goodmami** [comment]
This is an old ticket, but in the develop branch (which will become master), I've done away with the networkx backend for performance reasons. This means it's not as easy to make a d3-compatible javascript object, but it's not that hard, either. I'm doing it for Demophin (https://github.com/goodmami/demophin; see a demo here (while it's up): http://compling.hss.ntu.edu.sg/demophin/).

I'm going to close this with "wontfix", since I don't think an application-specific function like outputting d3 objects belongs in pyDelphin at this time (rather, it should go in the end application, as with Demophin).

That said, just ask if you want some help making your own d3 visualization using pyDelphin.

**Comment by alvations** [comment]
@goodmami Nice looking demo!!! Thanks Mike for all the hard work!!

For now I won't be working with DELPH-IN as much as I would like to because I'm wrapping up my MT related thesis. But I'll surely try it when i'm free =)

**Comment by goodmami** [comment]
Thanks!

I'll be showing it off at the summit this year. And a Ph.D. student at NTU might be taking over the helm after I leave. Feel free to add feature requests on the Demophin page.

Good luck with your thesis! I need to wrap up mine, as well. I look forward to reading or hearing about your results!
